[options]
pipelining = true
rustflags = ["-C link-arg=-fuse-ld=lld", "-C link-arg=-Wl,--compress-debug-sections=zlib", "-C force-frame-pointers=yes"]
rustc-wrapper = "sccache"

[profile.debug]
debug = 1

[profile.release]
debug = 1
incremental = true
lto = "thin"

[profile.release-full]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
debug = 1
debug-assertions = false
overflow-checks = false

[profile.release-size]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
debug = 1
debug-assertions = false
overflow-checks = false

[profile.release-tiny]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
debug = 1
debug-assertions = false
overflow-checks = false
